apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080

        env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://otel-collector.monitoring.svc:4317
        
          - name: OTEL_SERVICE_NAME
            value: addressbook
          
          - name: OTEL_TRACES_EXPORTER
            value: otlp
          
          - name: OTEL_LOGS_EXPORTER
            value: otlp

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
