apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: project1
spec:
  serviceAccountName: hello-app-sa
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
