apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx

  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: wildcard-tls
  
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-app
            port:
              number: 80
