apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app
  namespace: project1
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-app
            port:
              number: 80